export const FUNNEL_EVENT_NAMES = [
  "session_exit",
  "landing_page_viewed",
  "homepage_viewed",
  "therapist_directory_viewed",
  "paid_traffic_landed",
  "hero_finder_clicked",
  "hero_compare_clicked",
  "hero_booking_clicked",
  "hero_phone_clicked",
  "pricing_section_viewed",
  "insurance_section_viewed",
  "therapist_finder_started",
  "therapist_finder_step_completed",
  "therapist_finder_completed",
  "therapist_recommendation_viewed",
  "therapist_recommendation_profile_clicked",
  "therapist_recommendation_jane_clicked",
  "concern_selector_used",
  "therapist_card_viewed",
  "therapist_profile_clicked",
  "therapist_compare_started",
  "therapist_compare_completed",
  "directory_jane_clicked",
  "possibility_builder_viewed",
  "possibility_builder_started",
  "possibility_stage_completed",
  "possibility_reflection_viewed",
  "recommendation_profile_clicked",
  "recommendation_jane_clicked",
  "alternative_therapists_clicked",
  "possibility_builder_restarted",
  "phone_clicked",
  "request_help_opened",
  "request_help_submitted",
  "quiz_clicked",
  "consultation_page_viewed",
  "consultation_form_started",
  "consultation_step_viewed",
  "consultation_form_validation_failed",
  "consultation_request_clicked",
  "consultation_request_submitted",
  "consultation_jane_secondary_clicked",
  "quiz_page_viewed",
  "quiz_question_viewed",
  "quiz_question_answered",
  "quiz_back_clicked",
  "quiz_access_form_viewed",
  "quiz_access_form_started",
  "quiz_access_form_validation_failed",
  "quiz_started",
  "quiz_progressed",
  "quiz_completed",
  "quiz_intent_selected",
  "lead_details_submitted",
  "results_viewed",
  "therapist_match_viewed",
  "jane_booking_clicked",
  "contact_help_opened",
  "contact_help_submitted",
  "therapist_directory_clicked",
] as const;

export type FirstPartyFunnelEvent = (typeof FUNNEL_EVENT_NAMES)[number];

export const FUNNEL_PAGES = [
  "homepage",
  "therapist_directory",
  "therapist_profile",
  "quiz",
  "consultation",
  "sitewide",
] as const;

export const DEVICE_CATEGORIES = ["mobile", "tablet", "desktop"] as const;
